Update bootstrap - install packages conditionally
Only install packages when state file doesn't exist or when packages file
has changed. This reduces output when running bootstrap, leaving out
clutter.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -5,13 +5,19 @@
 eval "$(. /etc/os-release && typeset -p ID)"
 if [[ $ID == ol ]]; then
   sudo dnf config-manager --set-enabled ol9_developer_EPEL
-  sudo dnf upgrade -y || { echo "Failed"; return 1; }
-  source ~/.dotfiles/packages && sudo dnf install -y -- "${packages[@]}" || \
-    { echo "Failed: package update"; return 1; }
+  sudo dnf upgrade -y || { echo "Failed: packages update"; return 1; }
+  if ! cmp --silent ~/.dotfiles/packages $XDG_STATE_HOME/bootstrap_packages; then
+    source ~/.dotfiles/packages && sudo dnf install -y -- "${packages[@]}" || \
+      { echo "Failed: package installation"; return 1; }
+    command cp ~/.dotfiles/packages $XDG_STATE_HOME/bootstrap_packages
+  fi
 elif [[ $ID == debian ]]; then
-  sudo apt-get update && sudo apt-get upgrade -y || { echo "Failed"; return 1; }
-  source ~/.dotfiles/packages && sudo apt-get install -y -- "${packages[@]}" || \
-    { echo "Failed: package update"; return 1; }
+  sudo apt-get update && sudo apt-get upgrade -y || { echo "Failed: packages update"; return 1; }
+  if ! cmp --silent ~/.dotfiles/packages $XDG_STATE_HOME/bootstrap_packages; then
+    source ~/.dotfiles/packages && sudo apt-get install -y -- "${packages[@]}" || \
+      { echo "Failed: package installation"; return 1; }
+    command cp ~/.dotfiles/packages $XDG_STATE_HOME/bootstrap_packages
+  fi
 fi
 unset packages
 
@@ -59,9 +65,4 @@ if ! grep -qi microsoft /proc/version; then
 fi
 
 # Initialise shell
-if [[ $BASH_VERSION ]]; then
-  bind -f ~/.inputrc
-  source ~/.bash_profile
-elif [[ $ZSH_VERSION ]]; then
-  exec zsh
-fi
+exec $SHELL
