Improve nix package installation
Now only changes in nix.pkgs are acted on and packages get removed.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -2,6 +2,9 @@
 # vim: filetype=bash
 
 redc=$(tput setaf 1)
+gren=$(tput setaf 2)
+yelw=$(tput setaf 3)
+bold=$(tput bold)
 norm=$(tput sgr0)
 
 if ! command -v gum >/dev/null; then
@@ -48,6 +51,7 @@ if [[ $pkmngcmd ]]; then
 fi
 
 # Install/update Nix package manager
+# and install/uninstall packages
 if ! command -v nix  >/dev/null; then
   git -C ~/.dotfiles diff-index --quiet HEAD || stash=true
   [[ $stash ]] && git -C ~/.dotfiles stash push --quiet
@@ -62,10 +66,23 @@ if ! command -v nix  >/dev/null; then
 fi
 nix-channel --update
 if ! cmp --silent ~/.dotfiles/nix.pkgs $XDG_STATE_HOME/nix_packages; then
-  for nixpkg in $(egrep -v "[\s]*([#;].*|^$)" ./nix.pkgs); do
-    nix-env -iA $nixpkg && echo $nixpkg installed || \
-      { echo "${redc}Failed: $nixpkg nix package${norm}" >&2; return 1; }
+  installpkgs=("${(f)$(comm -2 -3 <(sort -u ~/.dotfiles/nix.pkgs) \
+    <(sort -u $XDG_STATE_HOME/nix_packages 2>/dev/null))}")
+  for nixpkg in ${installpkgs[@]}; do
+    nix-env -iA $nixpkg && \
+      echo "${gren}${nixpkg#nixpkgs.} installed${norm}" || \
+      { echo "${redc}Failed: ${nixpkg#nixpkgs.} nix package installation${norm}" >&2
+        return 1; }
   done
+  removepkgs=("${(f)$(comm -1 -3 <(sort -u ~/.dotfiles/nix.pkgs) \
+    <(sort -u $XDG_STATE_HOME/nix_packages 2>/dev/null))}")
+  for rmnixpkg in ${removepkgs[@]}; do
+    nix-env --uninstall ${rmnixpkg#nixpkgs.} && \
+      echo "${yelw}${rmnixpkg#nixpkgs.} uninstalled${norm}" || \
+      { echo "${redc}Failed: ${rmnixpkg#nixpkgs.} nix package removal${norm}" >&2
+        return 1; }
+  done
+  unset installpkgs removepkgs
   command cp ~/.dotfiles/nix.pkgs $XDG_STATE_HOME/nix_packages
 fi
 
