Make bootstrap stop on error
I did not notice stowing errors before as the script continued to run.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -6,21 +6,23 @@ eval "$(. /etc/os-release && typeset -p ID)"
 if [[ $ID == ol ]]; then
   sudo dnf config-manager --set-enabled ol9_developer_EPEL
   sudo dnf upgrade -y
-  sudo dnf install -y $(egrep -v "[\s]*([#;].*|^$)" ~/.dotfiles/packages)
+  sudo dnf install -y $(egrep -v "[\s]*([#;].*|^$)" ~/.dotfiles/packages) || \
+    { echo "Failed"; return 1; }
 elif [[ $ID == debian ]]; then
   sudo apt-get update && sudo apt-get upgrade -y
-  sudo apt-get install -y $(egrep -v "[\s]*([#;].*|^$)" ~/.dotfiles/packages)
+  sudo apt-get install -y $(egrep -v "[\s]*([#;].*|^$)" ~/.dotfiles/packages) || \
+    { echo "Failed"; return 1; }
 fi
 
 # Stow binaries
 if [[ $UID -ne 0 ]] && [[ $EUID -ne 0 ]]; then
-  sudo ~/.dotfiles/bin/scripts/stow-bin.sh
+  sudo ~/.dotfiles/bin/scripts/stow-bin.sh || { echo "Failed"; return 1; }
 else
-  ~/.dotfiles/bin/scripts/stow-bin.sh --nosudo
+  ~/.dotfiles/bin/scripts/stow-bin.sh --nosudo || { echo "Failed"; return 1; }
 fi
 
 # Stow dotfiles
-~/.dotfiles/bin/scripts/stow-dotfiles.sh
+~/.dotfiles/bin/scripts/stow-dotfiles.sh || { echo "Failed"; return 1; }
 
 # Setup/update antidote
 if [[ $ZSH_VERSION ]]; then
