Replace sdreader function if statement with case statement

diff --git a/shell/.hostinclude/hydra b/shell/.hostinclude/hydra
--- a/shell/.hostinclude/hydra
+++ b/shell/.hostinclude/hydra
@@ -2,11 +2,14 @@
 
 # Turn SD card reader on and off
 sdreader() {
-	if [[ $1 == on ]]; then
-		echo "2-3" | sudo tee /sys/bus/usb/drivers/usb/bind &>/dev/null && echo 'SD card reader on' || echo 'No change'
-	elif [[ $1 == off ]]; then
-		echo "2-3" | sudo tee /sys/bus/usb/drivers/usb/unbind &>/dev/null && echo 'SD card reader off' || echo 'No change'
-	fi
+	while :; do
+		case $1 in
+			on	) echo "2-3" | sudo tee /sys/bus/usb/drivers/usb/bind &>/dev/null && echo 'SD card reader on' || echo 'No change' ;;
+			off	) echo "2-3" | sudo tee /sys/bus/usb/drivers/usb/unbind &>/dev/null && echo 'SD card reader off' || echo 'No change' ;;
+			*	) echo "Error" ;;
+		esac
+		return
+	done
 }
 
 alias battery='date; sudo tlp-stat -b'
